[general]
fps_limit = 30
restart_wine_on_exit = true
refind_window_on_capture_error = true
show_fps = false
fps_report_interval_secs = 1

[wine]
command = "wine"
args = []
wallpaper_exe = "/home/aromatic/.local/share/Steam/steamapps/common/wallpaper_engine/wallpaper64.exe"

[capture]
wm_class_contains = "wallpaper"
# 如果 wine 参数含 -playInWindow，会自动从该参数推断标题关键字
# title_contains = "Wallpaper Engine 1"
# net_wm_pid = 12345
# debug_save_frame_png = "/tmp/we-layerd-capture.png"

[capture.output_window_map]
# "output-42" = 123456

[runtime]
mode = "wine_layerd"
wallpaper_type = "scene"
# video_file = "/path/to/video.mp4"

[cgroup]
enabled = false
mode = "detect" # detect | limit_wine
# memory_max = "2147483648" # bytes or "max"
# cpu_max = "50000 100000"  # quota period, or "max 100000"
