[general]
fps_limit = 30
restart_wine_on_exit = true
refind_window_on_capture_error = true

[wine]
command = "wine"
args = []
wallpaper_exe = "~/.local/share/Steam/steamapps/common/wallpaper_engine/wallpaper64.exe"

[capture]
wm_class_contains = "wallpaper"
# title_contains = "wallpaper"
# net_wm_pid = 12345
# debug_save_frame_png = "/tmp/we-layerd-capture.png"

[capture.output_window_map]
# "output-42" = 123456
